---
- name: Changing the server password to a random password
  hosts: all
  remote_user: root
  tasks:
    - name: Generate the password
      shell: openssl rand -base64 12 | cut -b 1-8  > ~/.openssl

    - name: modify passwd
      shell: echo `cat ~/.openssl` | passwd --stdin root

    - name: fetch file
      fetch:
        src: ~/.openssl
        dest: ~/fetch/openssl-{{ inventory_hostname }}
        flat: yes

    - name: delete pass file
      shell: rm -rf ~/.openssl
