---
- name: Changing the server password to a random password
  hosts: all
  remote_user: root
  tasks:
    - name: 1. Check the error in system booting messages
      command: dmesg -l err,crit,alert,emerg
      register: dmesg 
    - name: output dmesg
      debug:
        msg: "{{ dmesg.stdout.split('\n') }}"

