---
- name: Check the Server in KIDC (dmesg, /etc/rc.local, netstat, systemlog, /etc/hosts.allow, ...)
  hosts: all
  remote_user: root
  tasks:
    - name: 1. Check the error in system booting messages
      command: dmesg -l err,crit,alert,emerg
      register: dmesg_output

    - name: Output dmesg
      debug:
        msg: "{{ dmesg_output.stdout.split('\n') }}"

    - name: 2. Check the Routing Table, Port Interface
      command: netstat -nr
      register: netstatnr_output

    - name: Output netstatnr
      debug:
        msg: "{{ netstatnr_output.stdout.split('\n') }}"

    - name: 3. Check the date
      command: date
      register: date_output

    - name: Output date
      debug:
        msg: "{{ date_output.stdout.split('\n') }}"

    - name: 5. Check the disk free (mount, usage)
      command: df -h
      register: disk_output

    - name: Output disk
      debug:
        msg: "{{ disk_output.stdout.split('\n') }}"

    - name: 6. Check the OS Status (Memory, CPU, etc.)
      command: top -b -n 1
      register: top_output

    - name: Output top
      debug:
        msg: "{{ top_output.stdout.split('\n') }}"

    - name: 8. Check the /etc/rc.local file
      command: cat /etc/rc.local
      register: rclocal_output

    - name: Output rclocal
      debug:
        msg: "{{ rclocal_output.stdout.split('\n') }}"

    - name: 10. Check the iptables
      command: iptables -nL -v
      register: iptables_output

    - name: Output iptables
      debug:
        msg: "{{ iptables_output.stdout.split('\n') }}"

    - name: 11. Check the /etc/hosts.allow file
      command: cat /etc/hosts.allow
      register: hosts_output

    - name: Output hosts
      debug:
        msg: "{{ hosts_output.stdout.split('\n') }}"
